import Head from 'next/head'
import { searchArticleServiceWithFetch } from '../../services/articlesService'
import ShowArticle from '../../components/user/singleArticle/show'
import Sidebar from '../../components/user/singleArticle/sidebar'
import Comment from '../../components/user/singleArticle/comment'
import PageWrap from '../../components/global/wraps/page'

export default function SingleArticle ({article}) {

    return (
        <PageWrap>
            <Head>
                <title>{article.title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            
            <div className="grid grid-cols-12 gap-6">
                <aside className="xl:col-span-3 lg:col-span-4 col-span-12 lg:order-1 order-2">
                    <Sidebar />
                </aside>

                <main className="xl:col-span-9 lg:col-span-8 col-span-12 lg:order-2 order-1">
                    <ShowArticle article={article} />
                    <Comment />
                </main>
            </div>
        </PageWrap>
    )
}

export async function getServerSideProps ({params: {slug}}) {
    const {data} = await searchArticleServiceWithFetch('slug', slug)
    return {props: {article: data[0]}}
}

SingleArticle.existInLayout = ['sidebar']