import Head from 'next/head'
import { searchArticleServiceWithFetch } from '../../services/articlesService'
import ShowArticle from '../../components/primary/singleArticle/show'
import Comment from '../../components/primary/singleArticle/comment'
import PageWrap from '../../components/global/wraps/page'

export default function SingleArticle ({article}) {
    return (
        <PageWrap>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            
            <ShowArticle article={article} />
            <Comment />
        </PageWrap>
    )
}

export async function getServerSideProps ({params: {slug}}) {
    const {data} = await searchArticleServiceWithFetch('slug', slug)
    return {props: {article: data[0]}}
}