import { useEffect } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import Head from 'next/head'
import { setArticles } from '../../store/slices/articlesSlice'
import { setIsLoading } from '../../store/slices/globalSlice'
import ListArticles from '../../components/primary/articles/list'
import { getArticlesService } from '../../services/articlesService'
import MoreButton from '../../components/global/elements/moreButton'
import PageWrap from '../../components/global/wraps/page'

export default function Articles () {

    const {articles, pagination: {totalCount, currentPage}} = useSelector(state => state.articles)

    const dispatch = useDispatch()

    useEffect(() => {
        if (!articles.length) pageChangeHandler(1)
    }, [])

    const pageChangeHandler = async (page) => {
        try {
            dispatch(setIsLoading(true))
            const {data: {data, meta: {totalDocs, limit}}} = await getArticlesService(page, 'status:public')
            dispatch(setArticles({page, data, totalDocs, limit}))
        } finally {
            dispatch(setIsLoading(false))
        }
    }

    return (
        <PageWrap>
            <Head>
                <title>مقالات</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <ListArticles />
            <MoreButton text="مقالات بیشتر" onClick={() => pageChangeHandler(currentPage + 1)} isStill={articles.length < totalCount} />
        </PageWrap>
    )
}