import Head from 'next/head'
import PageWrap from '../../components/global/wraps/page'

export default function Login () {
    return (
        <PageWrap>
            <Head>
                <title>ورود</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            ورود
        </PageWrap>
    )
}