import { useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { toast } from 'react-toastify'
import { FullScreenCenterWrap } from '../../components/global/wraps'
import LogoSvg from '../../components/global/svg/logo'
import Button from '../../components/global/elements/button'
import InputForm from '../../components/global/form/input'
import { getTheme } from '../../modules/helperFunctions'
import { SUCCESSFUL_LOGIN } from '../../constants/responses'

export default function Login () {

    const router = useRouter()

    useEffect(() => {
        (localStorage?.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) ? window.document.documentElement.classList.add('dark'): window.document.documentElement.classList.remove('dark')
    }, [])

    const submitHandler = e => {
        e.preventDefault()
        toast.success(SUCCESSFUL_LOGIN, {...getTheme()})
        router.push('/panel')
    }

    return (
        <>
            <Head>
                <title>ورود | ثبت نام</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <FullScreenCenterWrap>
                <div className="bg-white dark:bg-gray-800/50 md:border border-gray-300/80 dark:border-gray-700/60 md:rounded-2xl p-8 w-full md:w-[400px]">

                    <form onSubmit={submitHandler}>
                        <LogoSvg onClick={() => router.push('/')} className="h-16 w-16 mx-auto -mt-2" />
                        <h1 className="text-center text-xl font-semibold text-gray-500 mt-6 mb-6">ورود | ثبت نام</h1>
                        
                        <InputForm label="لطفا شماره موبایل یا ایمیل خود را وارد کنید" dir="ltr" keyname="email" value="" inputHandler={(key, val) => {}} />
                        <Button type="submit" variant="primary" className="mt-3" widthFull>ورود</Button>
                    </form>
                    
                    <div className="flex justify-center text-xs text-gray-400 mt-3">
                        <span>ورود شما به معنای پذیرش</span>
                        <Link href="/terms"><a className="mx-1 text-indigo-600">شرایط</a></Link>
                        <span>و</span>
                        <Link href="/privacy"><a className="mx-1 text-indigo-600">قوانین حریم خصوصی</a></Link>
                        <span>است</span>
                    </div>

                </div>
            </FullScreenCenterWrap>
        </>
    )
}

Login.layout = null