import Head from 'next/head'
import PageWrap from '../../components/global/wraps/page'

export default function Register () {
    return (
        <PageWrap>
            <Head>
                <title>عضویت</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            عضویت
        </PageWrap>
    )
}