import { useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import useForm from '../../hooks/useForm'
import { toast } from 'react-toastify'
import { initialData, registerSchema } from '../../schemas/register'
import { ColumnGridWrap, InputForm, DateBirthForm, ButtonLoading } from '../../components/global/form'
import TitleForm from '../../components/user/auth/titleForm'
import { FORM_ERRORS, AXIOS_ERROR, SUCCESSFUL_OPERATION } from '../../constants/responses'
import { getTheme } from '../../modules/helperFunctions'
import TearmPrivacy from '../../components/user/auth/tearmPrivacy'
import { createUserService } from '../../services/users'
import LoginRegisterSwitch from '../../components/user/auth/loginRegisterSwitch'

export default function Register () {

    const {data, errors, setErrors, mapYupErrors, isSubmit, setIsSubmit, inputHandler} = useForm(initialData)

    const router = useRouter()

    useEffect(() => {
        (localStorage?.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) ? window.document.documentElement.classList.add('dark'): window.document.documentElement.classList.remove('dark')
    }, [])

    const submitHandler = async e => {
        try {
            e.preventDefault()
            setIsSubmit('create')
            await registerSchema().validate(data, {abortEarly: false})
            await create()
            setErrors({})
            toast.success(SUCCESSFUL_OPERATION, {...getTheme()})
            router.push('/auth/login')
        } catch (errors) {
            if (errors?.name === 'AxiosError') return toast.error(AXIOS_ERROR, {...getTheme()})
            setErrors(mapYupErrors(errors))
            toast.error(FORM_ERRORS, {...getTheme()})
        } finally {
            setIsSubmit('')
        }
    }

    const create = () => {
        return new Promise(async (resolve, reject) => {
            try {
                await createUserService({...data, created_at: Date.now()})
                return resolve()
            } catch (err) {
                return reject(err)
            }
        })
    }

    return (
        <>
            <Head>
                <title>ثبت نام</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="flex flex-col justify-center items-center md:my-8 animate-slow-1000">

                <div className="bg-white dark:bg-gray-800/50 md:border border-gray-300/80 dark:border-gray-700/60 md:rounded-2xl p-6 w-full md:w-[600px]">

                    <TitleForm title="ثبت نام" />

                    <form onSubmit={submitHandler}>
                        <ColumnGridWrap cols="2" gap="3">
                            <InputForm label="نام" keyname="name" value={data.name} error={errors.name} inputHandler={inputHandler} />
                            <InputForm label="فامیل" keyname="family" value={data.family} error={errors.family} inputHandler={inputHandler} />
                        </ColumnGridWrap>
                        <DateBirthForm label="تاریخ تولد" value={{day: data.day, month: data.month, year: data.year}} selected={{day: 3, month: 'دی', year: '1365'}} error={errors.day || errors.month || errors.year ? true : false} inputHandler={inputHandler} />
                        <InputForm label="ایمیل" keyname="email" value={data.email} error={errors.email} dir="ltr" inputHandler={inputHandler} />
                        <ColumnGridWrap cols="2" gap="3">
                            <InputForm label="رمز عبور" type="password" keyname="password" value={data.password} error={errors.password} dir="ltr" inputHandler={inputHandler} />
                            <InputForm label="تایید رمز عبور" type="password" keyname="passwordConfirmation" value={data.passwordConfirmation} error={errors.passwordConfirmation} dir="ltr" inputHandler={inputHandler} />
                        </ColumnGridWrap>
                        <ButtonLoading isSubmit={isSubmit} type="submit" widthFull className="mt-6">ثبت نام</ButtonLoading>
                    </form>

                    <LoginRegisterSwitch to="login" />

                </div>

                <TearmPrivacy />

            </div>
        </>
    )
}

Register.layout = null