import Head from 'next/head'
import PageWrap from '../components/global/wraps/page'

export default function AboutUs () {
    return (
        <PageWrap>
            <Head>
                <title>درباره ما</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            درباره ما
        </PageWrap>
    )
}