import Head from 'next/head'
import PageWrap from '../components/global/wraps/page'

export default function ContactUs () {
    return (
        <PageWrap>
            <Head>
                <title>ارتباط با ما</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            ارتباط با ما
        </PageWrap>
    )
}