import Head from 'next/head'
import PageWrap from '../components/global/wraps/page'

export default function ContactUs () {
    return (
        <>
            <Head>
                <title>ارتباط با ما</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <PageWrap>
                <div className="text-gray-500 dark:text-gray-200 px-4 md:px-0">ارتباط با ما</div>
            </PageWrap>
        </>
    )
}