import Head from 'next/head'
import PageWrap from '../components/global/wraps/page'
import BannerStart from '../components/user/home/bannerStart'
import Description from '../components/user/home/description'
import Swiper from '../components/user/home/swiper'

export default function Home () {
    return (
        <>
            <Head>
                <title>صفحه اصلی</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <PageWrap>
                <BannerStart />
            </PageWrap>

            <Description />

            <PageWrap>
                <Swiper />
            </PageWrap>
        </>
    )
}