import Head from 'next/head'
import PageWrap from '../../components/global/wraps/page'

export default function Panel () {
    return (
        <PageWrap>
            <Head>
                <title>پنل کاربری</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            پنل کاربری
        </PageWrap>
    )
}