import Head from 'next/head'
import { useTranslation } from 'react-i18next'

import PageWrap from '../../components/global/wraps/page'
import { StarSvg, DollarSvg, ListSvg } from '../../components/global/svg'

export default function Panel () {

    const {t, i18n: {language}} = useTranslation()

    return (
        <PageWrap variant="panel">
            <Head>
                <title>{t('menu.userPanel')}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="grid md:grid-cols-3 gap-6">
                <div className="flex justify-between items-center text-gray-400 bg-gray-100 dark:bg-gray-900 border dark:border-0 border-gray-200 px-3 py-5 rounded-lg">
                    <div>
                        <div className="text-lg font-semibold mb-2">{t('panel.mainPage.inventory')}</div>
                        <div className="text-gray-500 dark:text-gray-200 text-center text-2xl font-bold">{Number(1255).toLocaleString(language)}</div>
                    </div>
                    
                    <DollarSvg className="h-7 w-7 text-green-600" />
                </div>

                <div className="flex justify-between items-center text-gray-400 bg-gray-100 dark:bg-gray-900 border dark:border-0 border-gray-200 px-3 py-5 rounded-lg">
                    <div>
                        <div className="text-lg font-semibold mb-2">{t('panel.mainPage.score')}</div>
                        <div className="text-gray-500 dark:text-gray-200 text-center text-2xl font-bold">{Number(3781).toLocaleString(language)}</div>
                    </div>
                    
                    <StarSvg className="h-7 w-7 text-yellow-500" />
                </div>

                <div className="flex justify-between items-center text-gray-400 bg-gray-100 dark:bg-gray-900 border dark:border-0 border-gray-200 px-3 py-5 rounded-lg">
                    <div>
                        <div className="text-lg font-semibold mb-2">{t('panel.mainPage.todos')}</div>
                        <div className="text-gray-500 dark:text-gray-200 text-center text-2xl font-bold">{Number(1302).toLocaleString(language)}</div>
                    </div>
                    
                    <ListSvg className="h-7 w-7 text-purple-600" />
                </div>
            </div>

            <div className="pt-5 text-gray-500 dark:text-gray-300 text-justify leading-8">
                {t('panel.mainPage.text')}
            </div>
        </PageWrap>
    )
}

Panel.layout = 'panel'