import Head from 'next/head'
import PageWrap from '../../components/global/wraps/page'

export default function Notifications () {
    return (
        <PageWrap variant="panel">
            <Head>
                <title>اعلانات</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="text-gray-500 dark:text-gray-200">اعلانات</div>
        </PageWrap>
    )
}

Notifications.layout = 'panel'